spring:
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
  main:
    log-startup-info: false
    banner-mode: off